// ─── Route Path Constants ─────────────────────────────────────────────────────
// Always use these constants. Never hardcode route strings.

export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  GALLERY: '/gallery',
  CONTACT: '/contact',
  LOGIN: '/login',
  SIGNUP: '/signup',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/order-success',
  MY_ORDERS: '/my-orders',
  ENQUIRY: '/enquiry',
  PRODUCT_DETAILS: '/products/:id',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
  REFUND_POLICY: '/refund-policy',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_DETAILS: '/admin/orders/:id',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_INVENTORY: '/admin/inventory',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_REFUNDS: '/admin/refunds',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_LOGS: '/admin/activity-logs',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_PROFILE: '/admin/profile',
}

