const initialProducts = [
  {
    name: "AquaPure Personal Bottle",
    size: "500ml",
    price: 20,
    image: "/images/easytocarrygymtravell.png",
    category: "Personal",
    stock: 120,
    description: "Compact, easy-to-carry natural mineral water bottle. Perfect for gym, travel, and daily hydration on the go.",
    rating: 4.9,
    isFeatured: true,
  },
  {
    name: "AquaPure Pani pouch",
    size: "250ml",
    price: 8,
    image: "/images/pani_pouch_bottle.png",
    category: "Personal",
    stock: 100,
    description: "Compact, easy-to-carry natural mineral water bottle. Perfect for gym, travel, and daily hydration on the go.",
    rating: 4.5,
    isFeatured: true,
  },
  {
    name: "AquaPure Premium Everyday Bottle",
    size: "1 Liter",
    price: 40,
    image: "/images/1ltr.png",
    category: "Personal",
    stock: 150,
    description: "Our signature 1 Liter mineral water bottle enriched with essential minerals like Calcium, Magnesium, and Potassium.",
    rating: 5.0,
    isFeatured: true,
  },
  {
    name: "AquaPure Family Pack Bottle",
    size: "2 Liter",
    price: 70,
    image: "/images/2ltr.png",
    category: "Personal",
    stock: 80,
    description: "Convenient 2 Liter bottle designed for family dining tables, weekend road trips, and outdoor picnics.",
    rating: 4.7,
    isFeatured: false,
  },
  {
    name: "AquaPure Eco Handle Water Can",
    size: "5 Liter",
    price: 150,
    image: "/images/5ltr.png",
    category: "Bulk",
    stock: 60,
    description: "Medium-volume 5 Liter eco-friendly container equipped with an ergonomic pouring handle for kitchen use.",
    rating: 4.8,
    isFeatured: false,
  },
  {
    name: "AquaPure Heavy-Duty Dispenser Jar",
    size: "20 Liter Jar",
    price: 250,
    image: "/images/20ltrjar.png",
    category: "Bulk",
    stock: 100,
    description: "The gold standard 20 Liter dispenser jar for home and office water coolers. Multi-stage purified & sanitized.",
    rating: 4.9,
    isFeatured: true,
  },
  {
    name: "AquaPure Mini Event Party Pack (Box of 24)",
    size: "24 x 250ml",
    price: 360,
    image: "/images/minibottlesof250ml.png",
    category: "Bulk",
    stock: 40,
    description: "Bulk carton containing 24 mini 250ml mineral water bottles. Ideal for corporate meetings, weddings, and events.",
    rating: 4.8,
    isFeatured: false,
  },
  {
    name: "AquaPure Enterprise Supply Bundle",
    size: "10 x 20L Jars",
    price: 2200,
    image: "/images/20ltr10unitsjar.png",
    category: "Corporate",
    stock: 25,
    description: "Monthly subscription corporate package including 10 units of 20L jars with free scheduled office refills.",
    rating: 5.0,
    isFeatured: true,
  },
  {
    name: "AquaPure Smart Dispenser Cooler Stand + 20L Jar",
    size: "Dispenser + 20L",
    price: 1499,
    image: "/images/premium20ltrjar.png",
    category: "Corporate",
    stock: 30,
    description: "Premium countertop dispenser tap stand bundled with 1 initial 20 Liter mineral water jar.",
    rating: 4.9,
    isFeatured: false,
  },
];

module.exports = initialProducts;
